server:
  port: 8080

spring:
  application:
    #??????vm options???????":"????? ?????-Dunique-name=-zhangxf
    name: web-${unique-name:}
  cloud:
    nacos:
      discovery:
        server-addr: 101.43.144.47:8848
      password: nacos
      username: nacos

