server:
  port: 8080

spring:
  application:
    #配置vm参数：-Dunique-name=-zhangxf，":"不能省略 否则报错。
    name: web-${unique-name:}
  cloud:
    nacos:
      discovery:
        server-addr: 101.43.144.47:8848
      password: nacos
      username: nacos
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 101.43.144.47
      port: 6379
      password: 123456

framework:
  fastjson:
    safa-mode: true
#  cache:
#    redis:
#      value-timeout: 50000
#      bloom-filter:
#        user-register:
#          name: user_register_cache_penetration_bloom_filter${unique-name:}
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
